### ISSUE TITLE
[Research] Use HTML5 custom data attributes in place of html id's

### ISSUE THREAD

**Issue by theprivileges** [ksafranski/ColtJS#13]
Find out the pros/cons of using [HTML5 custom data attributes](http://html5doctor.com/html5-custom-data-attributes/) to create the element reference for a module. 
#### tentative html syntax

``` html
<div id="home" data-view="home">
   ...
</div>
```
#### binding in init method

``` javascript
document.querySelctorAll('[data-view="' + module + '"])';
```

**Comment by ksafranski** [comment]
Think this should move forward per our offline discussion:

```
<div data-view="home">...
```

**Comment by theprivileges** [comment]
Cool, thanks to @chemerisuk for the hint!

**Comment by theprivileges** [comment]
Will have to use `document.querySelector()` instead of `document.querySelectorAll()` because of the singularity of the **views**.

**Comment by ksafranski** [comment]
Sound reasoning on `document.querySelector()`, however, what if you wanted to utilize a view in more than one place?

The best example I can think of is something like pagination, having one at the top and one at the bottom of a list of (for example) search results...

```
<div data-view="pagination"></div>

<div data-view="search_results"></div>

<div data-view="pagination"></div>
```

**Comment by theprivileges** [comment]
Good thing I didn't close this ticket, felt I needed a peer review. Also need to look at the implications with `delegateEvents`.
