### ISSUE TITLE
View Composition?

### ISSUE THREAD

**Issue by sgentile** [ksafranski/ColtJS#15]
I see in the same a list of data-view divs - is there a concept of a data-view that can be swapped in with different views ?

**Comment by ksafranski** [comment]
I'm not 100% on your question, but the `data-view` attribute is a mapping. It allows Colt to make the association between the view and the DOM and subsequently render the template into the correct region. Through modifying the render process it is possible to instantiate templates into different (than their default mapping) or multiple `data-view` regions.

Please let me know if this helps, or if you can clarify your question I'll respond with more information.

**Comment by sgentile** [comment]
Swapping different views in and out of one div - view composition I should say

**Comment by ksafranski** [comment]
Swapping content (i.e. template) - yes; we actually [do that on the Colt website](https://github.com/Fluidbyte/ColtJS/blob/gh-pages/js/views/page_content.js#L20) to save on creating views for each content section.

Actually trading views, not currently. You would need a container for each view, so if I have

```
.../views
   ...view_a.js
   ...view_b.js
   ...view_c.js
```

I would need:

```
<div data-view="view_a" />
<div data-view="view_b" />
<div data-view="view_c" />
```

Similar to the way Backbone uses the `el` object to contain it's even bindings, etc, Colt binds events, render, etc to the dom element associated with the view.

That all being said, you could get around this by setting `Colt.scope.{view_name}.el` (and `$el` if using jQuery) manually.
